name: "Naabu Action"
description: "A fast port scanner written in go with a focus on reliability and simplicity."
branding:
  icon: "activity"
  color: "blue"

inputs:
  list:
    description: "List of hosts to perform port scan"
    required: true
    default: ""

  ports:
    description: "Ports to scan for (default - Top 100)"
    required: false
    default: ""

  output:
    description: "File to save output result"
    required: false
    default: "naabu.log"

  json:
    description: "Format to save of output file"
    required: false
    default: false

  rate:
    description: "Rate of port scan probes"
    required: false
    default: "1000"

  flags:
    description: "Additional naabu CLI flags to use"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get install libpcap-dev
        [ ! -x /home/runner/go/bin/naabu ] && go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
        [ ! -z ${{ inputs.list }} ] && echo "list=-iL ${{ inputs.list}}" >> $GITHUB_ENV
        [ ! -z ${{ inputs.ports }} ] && echo "ports=-p ${{ inputs.ports}}" >> $GITHUB_ENV
        [ ! -z ${{ inputs.output }} ] && echo "output=-o ${{ inputs.output}}" >> $GITHUB_ENV || echo "output=-o naabu.log" >> $GITHUB_ENV
        [ ! -z ${{ inputs.rate }} ] && echo "rate=-rate ${{ inputs.rate}}" >> $GITHUB_ENV
        [ ! -z "${{ inputs.flags }}" ] && echo "flags=${{ inputs.flags }}" >> $GITHUB_ENV
        ${{ inputs.json }} && echo "json=-json" >> $GITHUB_ENV
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        naabu \
          ${{ env.list }} \
          ${{ env.ports }} \
          ${{ env.output }} \
          ${{ env.json }} \
          ${{ env.rate }} \
          ${{ env.flags }}
      shell: bash
